# Generated by Django 5.2 on 2025-05-01 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_tasktarea3'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasktarea3',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
